
const MAD_LIB = getShortMadLib(); // When testing, try replacing with getLongMadLib()

/**
 * This function is called when the page is initially loaded.
 * It will generate inputs based on the contents of the MAD_LIB.fillers list.
 * Each input has an associated label and error text that begins as empty.
 */
function setup() {
    let parentNode = document.getElementById("madlib-questions");

    // TODO For each of MAD_LIB's `fillers`, generate an appropriate label and input.
    for (const [index, filler] of MAD_LIB.fillers.entries()) {
        // Create label
        let label = document.createElement("label");
        label.setAttribute("for", `input-${index}`);
        label.innerText = `Please enter a ${filler.type}: `;
        parentNode.appendChild(label);

        // Create input
        let input = document.createElement("input");
        input.setAttribute("type", "text");
        input.setAttribute("id", `input-${index}`);
        parentNode.appendChild(input);  
        // Create error text
        let errorText = document.createElement("div");
        errorText.setAttribute("id", `error-${index}`);
        errorText.setAttribute("class", "error-text");
        errorText.innerText = "";
        parentNode.appendChild(errorText);
    }
}

/**
 * This function is done for you.
 * This function is called anytime the user presses the "Generate!" button.
 * It first checks if the given inputs are valid. If they are valid,
 * the madlib is generated by calling the generateLib function.
 */
function generate() {
    if (validate()) {
        generateLib();
        alert("Success! Please see below for your MadLib :)");
    } else {
        alert("Uh oh, please check your form submission.")
    }
}

/**
 * This function is called by generate any time the user requests
 * generation and validation passes. Generate the `madlib-result` div
 * such that any existing HTML is replaced with the newest madlib contents.
 */
function generateLib() {
    // TODO Generate the madlib and insert it in `madlib-result`!
    let resultNode = document.getElementById("madlib-result");
    let filledInText = MAD_LIB.template;
    for (let i = 0; i < MAD_LIB.fillers.length; i++) {
        let input = document.getElementById(`input-${i}`);
        let userInput = input.value;
        let placeholder = `{${MAD_LIB.fillers[i].name}}`;
        filledInText = filledInText.replace(placeholder, userInput);
    }
    resultNode.innerText = filledInText;
}

/**
 * This function should check if any of the inputs have validation errors.
 * For each input, if it has validation errors, set the appropriate error text.
 * Otherwise, reset any error text that may exist. Use error text appropriate to
 * each form control, for exdample if validation fails on a quote, the error text
 * should say 'Please type 1 or more characters between quotes.' If the validation fails 
 * on a word, the error text should say 'Please type 1 or more letters, without spaces.'
 * 
 * Be sure to return true or false! Return true if all inputs are valid,
 * otherwise return false if ANY input is invalid.
 * 
 * @returns {boolean} true if form is valid, false otherwise.
 */
function validate() {
    let isValid = true;
    
    // TODO: If any inputs are invalid, set their error text.
    //       After checking ALL inputs, return true/false if
    //       the entire form was valid or not.
    for (let i = 0; i < MAD_LIB.fillers.length; i++) {
        let filler = MAD_LIB.fillers[i];
        let input = document.getElementById(`input-${i}`);
        let errorText = document.getElementById(`error-${i}`);
        let value = input.value.trim();
        let valid = true;
        if (filler.type === "word") {
            valid = /^[A-Za-z]+$/.test(value);
            if (!valid) {
                errorText.innerText = "Please type 1 or more letters, without spaces.";
                isValid = false;
            }
        } else if (filler.type === "quote") {
            valid = /^".+"$/.test(value);
            if (!valid) {
                errorText.innerText = 'Please type 1 or more characters between quotes.';
                isValid = false;
            }
        }
        if (valid) {
            errorText.innerText = "";
        }
    }
    return isValid;
}

// Don't remove this! It runs the setup function on page load.
window.onload = setup;
